### ISSUE TITLE
lib-find-the-path ignores foundry routePrefix for assets paths

### ISSUE THREAD

**Issue by js-murph** [dwonderley/lib-find-the-path#2] opened 2020-11-05 01:11 UTC
lib-find-the-path seems to ignore the routePrefix foundry option when configured for determining its default asset paths.

For example if routePrefix = "thing" all content is going to be at the base path of https://mydomain/thing/. The current behaviour of lib-find-the-path results in the following...

```
GET https://mydomain/modules/lib-find-the-path/scripts/pathManager.js 404
```

It should however be doing...

```
GET https://mydomain/thing/modules/lib-find-the-path/scripts/pathManager.js
```

**Comment by dwonderley** [comment] 2020-11-16 05:00
Sorry, I missed this issue. I'll look into it asap.

**Comment by js-murph** [comment] 2020-11-16 05:20
No problem, hardly an emergency, I'm keen to try out mookAI when it's fixed :D

**Comment by dwonderley** [comment] 2020-11-17 03:57
The problem is actually in the mookAI module, so I'm going to close this issue.

The problem is that the mook.js file is importing this library using a hard-coded path path to the module. I'll fix it there in the next patch.

Thanks for reporting this! I really appreciate it :)

**Closed as completed by dwonderley** 2020-11-17 03:57 UTC
Labels: bug
